# Generated by Django 5.1.1 on 2024-09-18 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandscapingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_model_name', models.CharField(max_length=100)),
                ('per_square_foot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.landscapingcompany')),
            ],
        ),
        migrations.AddField(
            model_name='landscapingcompany',
            name='pricing_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pricingmodel'),
        ),
    ]
